version: '3'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app 
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=askjdisdjoiwdjoiqdoandiad
    restart: always

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    restart: always
    tty: true
    stdin_open: true
